const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'

// 회원가입 액션지 입력 만들어보기.

export {USER_LOGIN_REQUEST, USER_LOGIN_FAIL, USER_LOGIN_SUCCESS, USER_SIGNUP_REQUEST}